name: Windows
on:
  push:
   
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  OVERRIDE_GIT_DESCRIBE: ${{ inputs.override_git_describe }}

jobs:
  windows-sign:
    # Builds binaries for windows_amd64
    name: Windows (64 Bit)
    runs-on: windows-2019
    steps:

      - name: Build
        shell: bash
        run: |
          curl -LOL https://github.com/duckdb/duckdb/releases/download/v1.2.0/duckdb_cli-windows-amd64.zip
          unzip duckdb_cli-windows-amd64.zip
          ls duckdb

      - name: Code signing with Software Trust Manager
        uses: digicert/ssm-code-signing@v1.0.0
